# file: .github/workflows/test-check.yml
name: test-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'npm'
      - run: make setup
      - run: make lint
      - run: make test
